spring:
  application:
    name: "PAYMENT-SERVICE"
h2:
console:
  enabled: true
datasource:
url:
username: sa

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
server:
   port: 9092
service-url:
      defaultZone:http://localhost:8761/eureka/

